<table border="0" cellspacing="0" cellpadding="5" width="100%">
<tr><td style="background-color: #8AB3FF; color: white; text-align: center; letter-spacing: .5ex; font-size: 125%">
Sullivan University <br />Computer Science Department<br />Hydra</td><td style="background-color: #8AB3FF; color: white; text-align: right">
<img src="images/logo.gif" alt="hydra" /></td></tr>
<tr>
<td class="tan">
<div class="nav">
<a href="index.php" title="Hydra Home">Home</a> |
<a href="CSC230.php" title="Website Design">CSC 230</a> |
<a href="CSC272.php" title="Principles of System Design">CSC 272</a> |
<a href="CSC210.php" title="Database Design">CSC 210</a> |
<a href="CSC322.php" title="Web Programming">CSC 322</a> |
<a href="CSC306.php" title="Systems Architecture">CSC 306</a> |
<a href="/moodle" title="COT Moodle Server">Moodle</a> |
<a href="/cms" title="Drupal Content Management">CMS</a>
</div></td><td class="tan" style="text-align: right"><?php echo date('F dS, Y'); ?></td></tr></table>

