<div id="sitemenu">

	<h2 class="hide">Sample menu:</h2>

	<ul>

		<li><a class="current" href="http://dev.cictspace.net">Home page</a></li>

		<li><a href="CSC210.php">CSC210</a></li>

		<li><a href="CSC230.php">CSC230</a></li>

		<li><a href="CSC272.php">CSC272</a></li>

		<li><a href="CSC322.php">CSC322</a></li>

		<li>&nbsp; </li>

		<!-- <li><a href="CSMaster.pdf">CS Schedule</a></li>

		<li><a href="OTMaster.pdf">OT Schedule</a></li> -->

		<li>&nbsp;</li>

		<li><a href="http://libguides.sullivan.edu/ICT/careers">Job Listing</a></li>

		<li class="hide"><a href="#header">Back to top</a></li>

	</ul>

	<br />



	<h2><a href="http://libguides.sullivan.edu/ICT/SATA">SATA</a></h2>

	<p>ACM Chapter <br />

	#102549 <br />

	<img src="images/acm_chapter.gif" alt="ACM chapter logo" width="100" height="100"/></p>

	<p><a href="http://goo.gl/m3GdA">

			Join ACM</a> today and give yourself the competitive edge in IT!</p>

		

	

</div>



<div id="extras">

	<h2>Sullivan Links</h2>

	<ul>

		<li><a href="http://www.sullivan.edu">Sullivan University</a></li>

		<li><a href="http://library.sullivan.edu">Sullivan Library</a></li>

		<li><a href="http://desktop.sullivan.edu">Virtual Desktop</a></li>

		<li><a href="http://itportal.sullivan.edu">IT Support</a></li>

		<li><a href="http://sullivan.angellearning.com">Angel</a></li>

		<li><a href="http://libguides.sullivan.edu/ICT/studentbenefits">Microsoft Imagine</a></li>

	</ul>



	<h2>Faculty Links</h2>

	<ul>

		<li><a href="#">Wilma Anthony</a></li>

		<li><a href="http://dev.cictspace.net/scordle">Scott Cordle</a></li>

		<!-- <li><a href="#">Beth Patterson</a></li> -->

		<li><a href="#">Travis Tiller</a></li>

		<li><a href="http://dev.cictspace.net/ttran">Dr. Tuan Tran</a></li>

	</ul>

	

	

</div>